---
# Based on http://wiki.ros.org/tf, 100ms (10hz) is a good value.
publish_frequency: 30

# tf bw /odom_combined and /map
map_2_odomCombined_trans: [-0.283, 1.417, 0.337]
map_2_odomCombined_quat: [0, 0, 0, 1]



...
