---
# Based on http://wiki.ros.org/tf, 100ms (10hz) is a good value.
publish_frequency: 100

# tf bw /odom_combined and /map
map_2_odomCombined_trans: [0.11874972534179687, 1.1272491455078124, 0.]

map_2_odomCombined_euler: [-1.57, 0, 0]
...
